### ISSUE TITLE
Update `fastify-request-context`

### ISSUE THREAD

**Issue by kibertoad** [goodvir/fastify-box#1]
I would recommend bumping `fastify-request-context` version to 2.1.0: there was an important fix for requests with body in 2.0.1 and 2.1.0 introduced a more convenient way to access the storage.

**Comment by goodvir** [comment]
Thanks for the recommendation, changes have been made in version [v1.0.1](https://github.com/goodvir/fastify-box/releases/tag/v1.0.1)
